# flake8: noqa
import generictester
import csv


token = "Bearer "+"eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCIsImtpZCI6InZUdzF6bi02cjFPcXg0NmNxRl9PMiJ9.eyJodHRwczovL2lkZW50LmV5ZXBvcC5haS9lbWFpbCI6ImFuZHlAZXllcG9wLmFpIiwiaHR0cHM6Ly9pZGVudC5leWVwb3AuYWkvYXV0aC1wcm92aWRlci1pZCI6ImF1dGgwfDY0YzQyYWI5ODc0ZGU3OGQyZTlmM2U0YSIsImh0dHBzOi8vaWRlbnQuZXllcG9wLmFpL3VzZXItdXVpZCI6ImZmOTFkNDYxNDYwZjExZWY4YTgyMGEzNTlhZTBiYjlkIiwiaHR0cHM6Ly9jbGFpbXMuZXllcG9wLmFpL2dyYW50cyI6W3sicGVybWlzc2lvbiI6ImFjY2VzczppbmZlcmVuY2UtYXBpIiwidGFyZ2V0IjoidXNlcjphdXRoMHw2NGM0MmFiOTg3NGRlNzhkMmU5ZjNlNGEifSx7InBlcm1pc3Npb24iOiJ1c2VyOmNvbXB1dGUiLCJ0YXJnZXQiOiJhY2NvdW50OjQ5MzI2ZjJlMDg1YTQ2YzM5YmE3M2Y5MWM1MmU0MzZjIn0seyJwZXJtaXNzaW9uIjoidXNlcjpjb21wdXRlIiwidGFyZ2V0IjoiYWNjb3VudDpiNDk2N2ZkY2M3ZWU0ZGYxYTA2YjM3NTU2ZGQyMWM2ZSJ9LHsicGVybWlzc2lvbiI6ImFjY2VzczpkYXRhc2V0cyIsInRhcmdldCI6ImFjY291bnQ6NDkzMjZmMmUwODVhNDZjMzliYTczZjkxYzUyZTQzNmMifSx7InBlcm1pc3Npb24iOiJhY2Nlc3M6ZGF0YXNldHMiLCJ0YXJnZXQiOiJhY2NvdW50OmI0OTY3ZmRjYzdlZTRkZjFhMDZiMzc1NTZkZDIxYzZlIn1dLCJodHRwczovL3N0YWdpbmcuZXllcG9wLnh5ei9ncm91cHMiOlsiUmVnaXN0cnlVc2VyIl0sImlzcyI6Imh0dHBzOi8vYXV0aDAuZXllcG9wLnh5ei8iLCJzdWIiOiJhdXRoMHw2NGM0MmFiOTg3NGRlNzhkMmU5ZjNlNGEiLCJhdWQiOiJodHRwczovL2Rldi1hcHAuZXllcG9wLmFpIiwiaWF0IjoxNzY1MzE3MzMzLCJleHAiOjE3NjUzMjQ1MzMsInNjb3BlIjoiYWNjZXNzOmRhdGFzZXRzIHVzZXI6Y29tcHV0ZSIsImF6cCI6IklVdDBwczJtYVdaVWRFbUVPUFJhUEpLdmtRVHM2WVVFIiwicGVybWlzc2lvbnMiOlsiYWNjZXNzOmRhdGFzZXRzIiwiYWNjZXNzOmluZmVyZW5jZS1hcGkiLCJhZG1pbjphcmdvY2QiLCJhZG1pbjpjbG91ZC1pbnN0YW5jZXMiLCJhZG1pbjpjbG91ZHMiLCJyZWFkOm1vZGVsLXVybHMiLCJyZWFkOnJlZ2lzdHJ5IiwidXNlcjpjb21wdXRlIl19.YxEA1lugfss1nRAKlMKAwKv-jZgzABIhiIi9mXe6pbCYDv7IfutQuRhly49jorColcrqDG8Wsft6bfDJ6HnZfVIvhxYgYF5KjDitzy2iOtbSPm8ivs68kgDQWq5IJwO6kLlEVCEM2K59J-u_AtQFgaHXHPN9PEOxnODJLl9LiCcGWBC4bqbq3K4FQiNUiKZb2v3OEmvsl4n6hQOUI9yv7uJDdS-rhXNJCCRNa0ebLUAixupXpz44bJE6HaBdkbozFqLBw8E7_o16goCJlVDUITCt-J819FLb1CIwbZHBR9xblZqm3kk4pnmeljdCMk9Fz7es-TG7G6XLuUrXgsyOzQ"

with open('testarray.csv', newline='') as csvfile:
    reader = csv.DictReader(csvfile)
    for row in reader:
        tag = row['Tag']
        text_prompt = row['Prompt']
        worker_release = row['Model']
        positive_image_folder_path = row['Positive Folder']
    
    generictester.TestPrompt(
        tag,
        text_prompt,
        positive_image_folder_path,
        token,
        worker_release=worker_release
    )